// <auto-generated />
namespace MVC_MyTimeTracker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class AddingProject_UpdatingTicket : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingProject_UpdatingTicket));
        
        string IMigrationMetadata.Id
        {
            get { return "201410050033531_AddingProject_UpdatingTicket"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
